spring:
  application:
    name: pizzaria
  profiles:
    active: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true